# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/exynos7885-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter a10 a20 a20e a30 a30s a40,$(TARGET_DEVICE)),)

endif
